tabelabrasileiro = ('Palmeiras', 'Atletico - MG', 'Corinthians', 'Coritiba', 'São Paulo', 'Athletico - PR', 'Botafogo', 'Flamengo', 'Santos', 'America - MG', 'Fluminense', 'Internacional', 'Avaí', 'Bragantino', 'Goiás', 'Chapecoense', 'Atlético - GO', 'Juventude', 'Ceará SC', 'Fortaleza')
print('='*35)
print(f'Lista de Times do Brasileiro {tabelabrasileiro}')
print('='*35)
print(f'Os 5 Primeiros São, em ordem : {tabelabrasileiro[:5]}')
print('='*35)
print(f'Os 4 últimos São: {tabelabrasileiro[-4:]}')
print('='*35)
print(f'Lista de Times em Ordem Alfabética: {sorted(tabelabrasileiro)}')
print('=-='*20)
print(f'O Time da Chapecoense Está na {tabelabrasileiro.index("Chapecoense")+1}ª Posição.')
